wandb_version: 1

batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 90
update_freq:
  desc: null
  value: 1
save_ckpt_freq:
  desc: null
  value: 5
model:
  desc: null
  value: beit_base_patch16_224
rel_pos_bias:
  desc: null
  value: true
abs_pos_emb:
  desc: null
  value: false
layer_scale_init_value:
  desc: null
  value: 0.1
input_size:
  desc: null
  value: 224
drop:
  desc: null
  value: 0.0
attn_drop_rate:
  desc: null
  value: 0.0
drop_path:
  desc: null
  value: 0.2
disable_eval_during_finetuning:
  desc: null
  value: true
model_ema:
  desc: null
  value: false
model_ema_decay:
  desc: null
  value: 0.9999
model_ema_force_cpu:
  desc: null
  value: false
opt:
  desc: null
  value: adamw
opt_eps:
  desc: null
  value: 1.0e-08
opt_betas:
  desc: null
  value: null
clip_grad:
  desc: null
  value: 3.0
momentum:
  desc: null
  value: 0.9
weight_decay:
  desc: null
  value: 0.05
weight_decay_end:
  desc: null
  value: null
lr:
  desc: null
  value: 0.003
layer_decay:
  desc: null
  value: 0.65
warmup_lr:
  desc: null
  value: 1.0e-06
min_lr:
  desc: null
  value: 1.0e-06
warmup_epochs:
  desc: null
  value: 5
warmup_steps:
  desc: null
  value: -1
color_jitter:
  desc: null
  value: 0.4
aa:
  desc: null
  value: rand-m9-mstd0.5-inc1
smoothing:
  desc: null
  value: 0.1
train_interpolation:
  desc: null
  value: bicubic
crop_pct:
  desc: null
  value: null
reprob:
  desc: null
  value: 0.25
remode:
  desc: null
  value: pixel
recount:
  desc: null
  value: 1
resplit:
  desc: null
  value: false
mixup:
  desc: null
  value: 0
cutmix:
  desc: null
  value: 0
cutmix_minmax:
  desc: null
  value: null
mixup_prob:
  desc: null
  value: 1.0
mixup_switch_prob:
  desc: null
  value: 0.5
mixup_mode:
  desc: null
  value: batch
finetune:
  desc: null
  value: https://github.com/addf400/files/releases/download/v1.0/beit_base_patch16_224_pt22k.pth
model_key:
  desc: null
  value: model|module
model_prefix:
  desc: null
  value: ''
init_scale:
  desc: null
  value: 0.001
use_mean_pooling:
  desc: null
  value: true
disable_weight_decay_on_rel_pos_bias:
  desc: null
  value: false
data_path:
  desc: null
  value: /home/shubhamp/Desktop/clf_emarg_data
eval_data_path:
  desc: null
  value: /home/shubhamp/Desktop/clf_emarg_data/val
nb_classes:
  desc: null
  value: 2
imagenet_default_mean_and_std:
  desc: null
  value: false
data_set:
  desc: null
  value: image_folder
output_dir:
  desc: null
  value: /home/shubhamp/Downloads/unilm/beit/beit_ckpt
log_dir:
  desc: null
  value: null
device:
  desc: null
  value: cuda
seed:
  desc: null
  value: 0
resume:
  desc: null
  value: ''
auto_resume:
  desc: null
  value: true
save_ckpt:
  desc: null
  value: true
start_epoch:
  desc: null
  value: 0
eval:
  desc: null
  value: false
dist_eval:
  desc: null
  value: false
num_workers:
  desc: null
  value: 10
pin_mem:
  desc: null
  value: true
world_size:
  desc: null
  value: 1
local_rank:
  desc: null
  value: -1
dist_on_itp:
  desc: null
  value: false
dist_url:
  desc: null
  value: env://
enable_deepspeed:
  desc: null
  value: true
deepspeed:
  desc: null
  value: false
deepspeed_config:
  desc: null
  value: null
deepscale:
  desc: null
  value: false
deepscale_config:
  desc: null
  value: null
deepspeed_mpi:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714742880.0
    t:
      1:
      - 1
      - 41
      - 49
      - 51
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 51
      - 55
      - 63
      3:
      - 16
      - 17
      - 23
      - 37
      4: 3.8.19
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
